import { NewsItem } from './types';

export const demoNews: NewsItem[] = [
  {
    id: '1',
    title: 'GPT-5 Release Imminent as OpenAI Reveals New Reasoning Capabilities',
    summary: 'OpenAI announces that GPT-5 will feature groundbreaking multi-step reasoning, real-time web access, and improved code generation that could reshape how developers build software.',
    source: 'TechCrunch',
    category: 'ai',
    url: '#',
    publishedAt: new Date().toISOString(),
    readTime: 4,
  },
  {
    id: '2',
    title: 'Bitcoin Surges Past $95K on ETF Inflows',
    summary: 'Institutional demand for Bitcoin ETFs drives the price to new highs, with BlackRock\'s IBIT seeing record daily inflows of $1.2 billion.',
    source: 'CoinDesk',
    category: 'crypto',
    url: '#',
    publishedAt: new Date().toISOString(),
    readTime: 3,
  },
  {
    id: '3',
    title: 'Nintendo Switch 2 Pre-Orders Sell Out in Under 5 Minutes',
    summary: 'The highly anticipated successor to the Switch breaks pre-order records globally. Key features include 4K output, magnetic Joy-Cons, and backward compatibility.',
    source: 'IGN',
    category: 'gaming',
    url: '#',
    publishedAt: new Date().toISOString(),
    readTime: 3,
  },
  {
    id: '4',
    title: 'AI Code Editor Cursor Raises $400M at $9B Valuation',
    summary: 'The VS Code fork that uses AI pair programming has become one of the fastest-growing developer tools ever, now used by over 2 million developers daily.',
    source: 'TechCrunch',
    category: 'startups',
    url: '#',
    publishedAt: new Date().toISOString(),
    readTime: 5,
  },
  {
    id: '5',
    title: 'Notion Launches AI-Powered Workflows to Rival Zapier',
    summary: 'Notion\'s new automation layer lets users build complex workflows with natural language, connecting databases, docs, and external APIs without code.',
    source: 'Product Hunt',
    category: 'productivity',
    url: '#',
    publishedAt: new Date().toISOString(),
    readTime: 4,
  },
  {
    id: '6',
    title: 'Google DeepMind\'s Gemini 2.5 Achieves PhD-Level Science Reasoning',
    summary: 'The latest Gemini model demonstrates remarkable ability to solve complex scientific problems, outperforming human experts in chemistry and physics benchmarks.',
    source: 'The Verge',
    category: 'ai',
    url: '#',
    publishedAt: new Date().toISOString(),
    readTime: 6,
  },
  {
    id: '7',
    title: 'Ethereum Layer 2 Fees Drop Below $0.001 After Dencun Upgrade',
    summary: 'The Dencun upgrade\'s blob transactions have dramatically reduced costs on Arbitrum, Optimism, and Base, making DeFi accessible to everyday users.',
    source: 'CoinDesk',
    category: 'crypto',
    url: '#',
    publishedAt: new Date().toISOString(),
    readTime: 4,
  },
  {
    id: '8',
    title: 'Indie Game "Hollow Drift" Becomes Surprise Steam Hit',
    summary: 'A solo developer\'s atmospheric roguelike has sold over 500K copies in its first week, blending Hades-like combat with procedural storytelling.',
    source: 'IGN',
    category: 'gaming',
    url: '#',
    publishedAt: new Date().toISOString(),
    readTime: 3,
  },
  {
    id: '9',
    title: 'Linear Launches AI Triage to Auto-Prioritize Engineering Tasks',
    summary: 'The popular project management tool now uses AI to automatically categorize, prioritize, and assign incoming issues based on team patterns and urgency signals.',
    source: 'Product Hunt',
    category: 'productivity',
    url: '#',
    publishedAt: new Date().toISOString(),
    readTime: 3,
  },
  {
    id: '10',
    title: 'YC-backed Startup Builds "GitHub for Hardware"',
    summary: 'Flux raises $18M to bring version control, collaboration, and CI/CD workflows to hardware engineering teams designing PCBs and mechanical parts.',
    source: 'Hacker News',
    category: 'startups',
    url: '#',
    publishedAt: new Date().toISOString(),
    readTime: 4,
  },
];
