import { NewsItem, Narrative } from './types';

const hours = (h: number) => {
  const d = new Date();
  d.setHours(d.getHours() - h, Math.floor(Math.random() * 60));
  return d.toISOString();
};

export const demoNarratives: Narrative[] = [
  {
    id: 'nar-1',
    title: 'AI Model War Escalates',
    whyItMatters: 'GPT-5, Claude 4, and Llama 4 all launched within weeks. Competition is driving costs down and capabilities up at unprecedented speed.',
    whyItMattersTh: 'GPT-5, Claude 4 และ Llama 4 เปิดตัวภายในไม่กี่สัปดาห์ การแข่งขันกำลังลดต้นทุนและเพิ่มขีดความสามารถอย่างรวดเร็ว',
    articleCount: 4,
    category: 'ai',
    momentum: 'Hot',
    articleIds: ['ts-2', 'ai-1', 'ai-4', 'ai-5'],
  },
  {
    id: 'nar-2',
    title: 'Institutional Crypto Adoption Accelerating',
    whyItMatters: 'BlackRock ETF inflows, RWA tokenization, and ETH L2 growth signal crypto is crossing from speculation to infrastructure.',
    whyItMattersTh: 'กระแสเงินไหลเข้า ETF ของ BlackRock, การ tokenize สินทรัพย์จริง และการเติบโตของ ETH L2 ส่งสัญญาณว่าคริปโตกำลังเปลี่ยนจากเก็งกำไรสู่โครงสร้างพื้นฐาน',
    articleCount: 4,
    category: 'crypto',
    momentum: 'Rising',
    articleIds: ['ts-3', 'cr-1', 'cr-5', 'cr-2'],
  },
  {
    id: 'nar-3',
    title: 'Fed Pivot Reshaping Markets',
    whyItMatters: 'Rate hold with dovish signals is lifting equities, gold, and crypto simultaneously. A regime change in monetary policy is underway.',
    whyItMattersTh: 'การคงอัตราดอกเบี้ยพร้อมสัญญาณผ่อนคลายกำลังดันหุ้น ทองคำ และคริปโตขึ้นพร้อมกัน การเปลี่ยนแปลงนโยบายการเงินกำลังเกิดขึ้น',
    articleCount: 4,
    category: 'macro',
    momentum: 'Hot',
    articleIds: ['ts-1', 'inv-4', 'inv-5', 'inv-1'],
  },
  {
    id: 'nar-4',
    title: 'DePIN Goes Mainstream',
    whyItMatters: 'Decentralized physical infrastructure is generating real revenue. Helium crossed 2M hotspots, proving the model works beyond speculation.',
    whyItMattersTh: 'โครงสร้างพื้นฐานทางกายภาพแบบกระจายศูนย์กำลังสร้างรายได้จริง Helium มี hotspot กว่า 2 ล้านจุด พิสูจน์ว่าโมเดลนี้ใช้ได้จริง',
    articleCount: 2,
    category: 'crypto',
    momentum: 'Watchlist',
    articleIds: ['cr-6', 'cr-7'],
  },
];

export const demoNews: NewsItem[] = [
  // ── TOP SIGNALS ──
  {
    id: 'ts-1',
    title: 'Fed Holds Rates Steady, Signals One Cut Before Year-End',
    summary: 'The Federal Reserve maintained its benchmark rate at 5.25–5.50%, with Chair Powell noting progress on inflation but wanting "greater confidence" before cutting.',
    source: 'Bloomberg',
    category: 'macro',
    subtopic: 'Central Bank',
    url: '#',
    publishedAt: hours(1),
    readTime: 4,
    isTopSignal: true,
    impactLevel: 'high',
    marketDirection: 'bullish',
    badges: ['Breaking', 'High Impact', 'Macro'],
    narrativeId: 'nar-3',
    signalScore: 95,
  },
  {
    id: 'ts-2',
    title: 'OpenAI Launches GPT-5 with Real-Time Reasoning and Agentic Tools',
    summary: 'GPT-5 introduces multi-step planning, autonomous tool use, and a 1M-token context window. Early benchmarks show PhD-level performance.',
    source: 'TechCrunch',
    category: 'ai',
    subtopic: 'Models',
    url: '#',
    publishedAt: hours(2),
    readTime: 5,
    isTopSignal: true,
    impactLevel: 'high',
    marketDirection: 'bullish',
    badges: ['Breaking', 'High Impact'],
    narrativeId: 'nar-1',
    signalScore: 92,
  },
  {
    id: 'ts-3',
    title: 'Bitcoin Breaks $100K as Institutional ETF Inflows Hit Record',
    summary: 'BTC surpassed $100,000 for the first time as BlackRock\'s IBIT recorded $2.1B in single-day inflows.',
    source: 'CoinDesk',
    category: 'crypto',
    subtopic: 'L1',
    url: '#',
    publishedAt: hours(1),
    readTime: 3,
    isTopSignal: true,
    impactLevel: 'high',
    marketDirection: 'bullish',
    badges: ['Breaking', 'High Impact', 'On-chain'],
    narrativeId: 'nar-2',
    signalScore: 98,
  },
  {
    id: 'ts-4',
    title: 'NVIDIA Surpasses Apple as World\'s Most Valuable Company',
    summary: 'NVIDIA\'s market cap reached $3.8 trillion on AI chip demand, overtaking Apple.',
    source: 'CNBC',
    category: 'tech-stocks',
    subtopic: 'Tech Stocks',
    url: '#',
    publishedAt: hours(3),
    readTime: 3,
    isTopSignal: true,
    impactLevel: 'high',
    marketDirection: 'bullish',
    badges: ['Breaking', 'High Impact', 'Earnings'],
    signalScore: 90,
  },

  // ── AI ──
  {
    id: 'ai-1',
    title: 'Anthropic\'s Claude 4 Achieves New State-of-the-Art in Coding Benchmarks',
    summary: 'Claude 4 scores 94.2% on SWE-bench, surpassing all competitors with "extended thinking" that shows its reasoning chain.',
    source: 'The Information',
    category: 'ai',
    subtopic: 'Models',
    url: '#',
    publishedAt: hours(3),
    readTime: 4,
    impactLevel: 'high',
    marketDirection: 'neutral',
    badges: ['Rising'],
    narrativeId: 'nar-1',
    signalScore: 85,
  },
  {
    id: 'ai-2',
    title: 'Google DeepMind Publishes Breakthrough in Protein-Drug Interaction',
    summary: 'AlphaFold 3 predicts drug-protein interactions, potentially cutting discovery timelines from years to months.',
    source: 'MIT Tech Review',
    category: 'ai',
    subtopic: 'Research',
    url: '#',
    publishedAt: hours(4),
    readTime: 6,
    impactLevel: 'medium',
    marketDirection: 'bullish',
    badges: ['Narrative'],
    signalScore: 78,
  },
  {
    id: 'ai-3',
    title: 'AI Code Editor Cursor Raises $400M at $9B Valuation',
    summary: 'The VS Code fork powered by AI pair programming is now used by 3 million developers daily.',
    source: 'TechCrunch',
    category: 'ai',
    subtopic: 'Startups',
    url: '#',
    publishedAt: hours(5),
    readTime: 4,
    impactLevel: 'medium',
    marketDirection: 'neutral',
    badges: ['Rising'],
    signalScore: 72,
  },
  {
    id: 'ai-4',
    title: 'Meta Releases Llama 4 Maverick Open-Source with MoE Architecture',
    summary: 'Llama 4 uses mixture-of-experts with 400B total but 17B active params. Rivals GPT-4o at fraction of compute.',
    source: 'VentureBeat',
    category: 'ai',
    subtopic: 'Models',
    url: '#',
    publishedAt: hours(6),
    readTime: 5,
    impactLevel: 'medium',
    marketDirection: 'neutral',
    badges: ['Narrative'],
    narrativeId: 'nar-1',
    signalScore: 70,
  },
  {
    id: 'ai-5',
    title: 'Microsoft Integrates AI Agents Into Every Office 365 App',
    summary: 'Copilot Agents can autonomously draft reports, schedule meetings, and manage email across the full Office suite.',
    source: 'The Verge',
    category: 'ai',
    subtopic: 'Companies',
    url: '#',
    publishedAt: hours(7),
    readTime: 4,
    impactLevel: 'medium',
    marketDirection: 'bullish',
    signalScore: 68,
  },

  // ── CRYPTO ──
  {
    id: 'cr-1',
    title: 'Ethereum Layer 2 TVL Surpasses $80B After Base and Arbitrum Surge',
    summary: 'Combined L2 TVL hit an all-time high as Base processed 15M daily transactions with blob fees under $0.01.',
    source: 'The Block',
    category: 'crypto',
    subtopic: 'L2',
    url: '#',
    publishedAt: hours(2),
    readTime: 4,
    impactLevel: 'high',
    marketDirection: 'bullish',
    badges: ['Rising', 'On-chain'],
    narrativeId: 'nar-2',
    signalScore: 82,
  },
  {
    id: 'cr-2',
    title: 'Uniswap v4 Hooks Unlock Custom AMM Logic, TVL Jumps 40%',
    summary: 'New hooks system enables dynamic fees, TWAP orders, and on-chain limit orders—driving a wave of DeFi innovation.',
    source: 'Decrypt',
    category: 'crypto',
    subtopic: 'DeFi',
    url: '#',
    publishedAt: hours(3),
    readTime: 4,
    impactLevel: 'medium',
    marketDirection: 'bullish',
    badges: ['On-chain'],
    signalScore: 75,
  },
  {
    id: 'cr-3',
    title: 'Polymarket Hits $500M Monthly Volume Ahead of Elections',
    summary: 'Record engagement as users bet on political, economic, and tech outcomes. US regulatory clarity boosts adoption.',
    source: 'CoinDesk',
    category: 'crypto',
    subtopic: 'Prediction Markets',
    url: '#',
    publishedAt: hours(4),
    readTime: 3,
    impactLevel: 'medium',
    marketDirection: 'neutral',
    badges: ['Rising'],
    signalScore: 70,
  },
  {
    id: 'cr-4',
    title: 'Solana Memecoin Frenzy: New Token Hits $2B Market Cap in 48 Hours',
    summary: 'Community-driven memecoin captures viral attention, raising questions about speculation vs. genuine community building.',
    source: 'Decrypt',
    category: 'crypto',
    subtopic: 'Memecoins',
    url: '#',
    publishedAt: hours(5),
    readTime: 3,
    impactLevel: 'low',
    marketDirection: 'neutral',
    signalScore: 35,
  },
  {
    id: 'cr-5',
    title: 'BlackRock Tokenizes $2B Treasury Fund on Ethereum via Securitize',
    summary: 'The world\'s largest asset manager expands BUIDL, signaling RWA tokenization is moving from pilot to production.',
    source: 'Bloomberg',
    category: 'crypto',
    subtopic: 'RWA',
    url: '#',
    publishedAt: hours(5),
    readTime: 4,
    impactLevel: 'high',
    marketDirection: 'bullish',
    badges: ['High Impact', 'Narrative'],
    narrativeId: 'nar-2',
    signalScore: 88,
  },
  {
    id: 'cr-6',
    title: 'Helium Network Crosses 2M Hotspots as DePIN Gains Traction',
    summary: 'Decentralized wireless infrastructure expands with 500K Helium Mobile subscribers. Revenue-generating DePIN attracts institutions.',
    source: 'The Block',
    category: 'crypto',
    subtopic: 'DePIN',
    url: '#',
    publishedAt: hours(6),
    readTime: 4,
    impactLevel: 'medium',
    marketDirection: 'bullish',
    badges: ['Narrative'],
    narrativeId: 'nar-4',
    signalScore: 65,
  },
  {
    id: 'cr-7',
    title: 'Immutable zkEVM Sees 10x Growth in Gaming Transactions',
    summary: 'AAA studios deploy on Immutable\'s gaming L2, with transactions jumping from 2M to 20M monthly.',
    source: 'CoinDesk',
    category: 'crypto',
    subtopic: 'GameFi',
    url: '#',
    publishedAt: hours(7),
    readTime: 3,
    impactLevel: 'low',
    marketDirection: 'bullish',
    narrativeId: 'nar-4',
    signalScore: 55,
  },
  {
    id: 'cr-8',
    title: 'Sui and Aptos Lead New Wave of Move-Based L1 Adoption',
    summary: 'Move-language blockchains see DeFi TVL double in 30 days. Developers praise safety guarantees and parallel execution.',
    source: 'The Block',
    category: 'crypto',
    subtopic: 'Altcoins',
    url: '#',
    publishedAt: hours(8),
    readTime: 4,
    impactLevel: 'medium',
    marketDirection: 'bullish',
    badges: ['Rising'],
    signalScore: 60,
  },

  // ── INVESTMENT / MACRO / COMMODITIES ──
  {
    id: 'inv-1',
    title: 'Gold Hits All-Time High of $2,850/oz on Geopolitical Uncertainty',
    summary: 'Safe-haven demand drives gold to record levels as central banks continue accumulating reserves.',
    source: 'Reuters',
    category: 'commodities',
    subtopic: 'Gold',
    url: '#',
    publishedAt: hours(2),
    readTime: 3,
    impactLevel: 'high',
    marketDirection: 'bullish',
    badges: ['High Impact', 'Macro'],
    narrativeId: 'nar-3',
    signalScore: 85,
  },
  {
    id: 'inv-2',
    title: 'Silver Surges 8% as Industrial AI Demand Outpaces Mining Supply',
    summary: 'Silver\'s dual role as precious metal and industrial input creates a structural supply deficit for the first time in a decade.',
    source: 'Financial Times',
    category: 'commodities',
    subtopic: 'Silver',
    url: '#',
    publishedAt: hours(3),
    readTime: 4,
    impactLevel: 'medium',
    marketDirection: 'bullish',
    badges: ['Rising'],
    signalScore: 72,
  },
  {
    id: 'inv-3',
    title: 'Magnificent 7 Rally: Combined Market Cap Exceeds $18 Trillion',
    summary: 'Apple, Microsoft, NVIDIA, Amazon, Alphabet, Meta, and Tesla collectively gained $1.2T in Q1 on AI spending.',
    source: 'CNBC',
    category: 'tech-stocks',
    subtopic: 'Tech Stocks',
    url: '#',
    publishedAt: hours(4),
    readTime: 5,
    impactLevel: 'high',
    marketDirection: 'bullish',
    badges: ['High Impact', 'Earnings'],
    signalScore: 88,
  },
  {
    id: 'inv-4',
    title: 'US Inflation Drops to 2.4%, Lowest Since Early 2021',
    summary: 'CPI shows disinflation from falling energy prices. Core services at 3.8% keeps Fed cautious.',
    source: 'Bloomberg',
    category: 'macro',
    subtopic: 'Macro Economy',
    url: '#',
    publishedAt: hours(5),
    readTime: 4,
    impactLevel: 'high',
    marketDirection: 'bullish',
    badges: ['Macro', 'High Impact'],
    narrativeId: 'nar-3',
    signalScore: 90,
  },
  {
    id: 'inv-5',
    title: 'S&P 500 Closes Above 6,000 for First Time in History',
    summary: 'AI infrastructure spending and strong earnings push the index past a psychological milestone.',
    source: 'Reuters',
    category: 'investment',
    subtopic: 'Market Movements',
    url: '#',
    publishedAt: hours(3),
    readTime: 3,
    impactLevel: 'high',
    marketDirection: 'bullish',
    badges: ['Breaking', 'High Impact'],
    narrativeId: 'nar-3',
    signalScore: 87,
  },
  {
    id: 'inv-6',
    title: 'China Stimulus Package Boosts Emerging Market Sentiment',
    summary: 'Beijing announces $500B infrastructure plan. Hang Seng rallies 4% as global funds rotate into Chinese equities.',
    source: 'Financial Times',
    category: 'macro',
    subtopic: 'Macro Economy',
    url: '#',
    publishedAt: hours(6),
    readTime: 4,
    impactLevel: 'medium',
    marketDirection: 'bullish',
    badges: ['Macro'],
    signalScore: 73,
  },
];
