import { NewsItem } from './types';

const hours = (h: number) => {
  const d = new Date();
  d.setHours(d.getHours() - h, Math.floor(Math.random() * 60));
  return d.toISOString();
};

export const demoNews: NewsItem[] = [
  // ── TOP SIGNALS ──
  {
    id: 'ts-1',
    title: 'Fed Holds Rates Steady, Signals One Cut Before Year-End',
    summary: 'The Federal Reserve maintained its benchmark rate at 5.25–5.50%, with Chair Powell noting progress on inflation but wanting "greater confidence" before cutting. Markets rallied on the dovish tone.',
    source: 'Bloomberg',
    category: 'investment',
    subtopic: 'Macro Economy',
    url: '#',
    publishedAt: hours(1),
    readTime: 4,
    isTopSignal: true,
  },
  {
    id: 'ts-2',
    title: 'OpenAI Launches GPT-5 with Real-Time Reasoning and Agentic Tools',
    summary: 'GPT-5 introduces multi-step planning, autonomous tool use, and a 1M-token context window. Early benchmarks show PhD-level performance across science and coding tasks.',
    source: 'TechCrunch',
    category: 'ai',
    subtopic: 'Models',
    url: '#',
    publishedAt: hours(2),
    readTime: 5,
    isTopSignal: true,
  },
  {
    id: 'ts-3',
    title: 'Bitcoin Breaks $100K as Institutional ETF Inflows Hit Record',
    summary: 'BTC surpassed the $100,000 mark for the first time as BlackRock\'s IBIT recorded $2.1B in single-day inflows. Total crypto market cap now exceeds $4 trillion.',
    source: 'CoinDesk',
    category: 'crypto',
    subtopic: 'L1/L2',
    url: '#',
    publishedAt: hours(1),
    readTime: 3,
    isTopSignal: true,
  },
  {
    id: 'ts-4',
    title: 'NVIDIA Surpasses Apple as World\'s Most Valuable Company',
    summary: 'NVIDIA\'s market cap reached $3.8 trillion on AI chip demand, overtaking Apple. The company announced next-gen Blackwell Ultra GPUs shipping Q3.',
    source: 'CNBC',
    category: 'investment',
    subtopic: 'Tech Stocks',
    url: '#',
    publishedAt: hours(3),
    readTime: 3,
    isTopSignal: true,
  },

  // ── AI ──
  {
    id: 'ai-1',
    title: 'Anthropic\'s Claude 4 Achieves New State-of-the-Art in Coding Benchmarks',
    summary: 'Claude 4 scores 94.2% on SWE-bench, surpassing all competitors. The model introduces "extended thinking" that shows its reasoning chain before answering.',
    source: 'The Information',
    category: 'ai',
    subtopic: 'Models',
    url: '#',
    publishedAt: hours(3),
    readTime: 4,
  },
  {
    id: 'ai-2',
    title: 'Google DeepMind Publishes Breakthrough in Protein-Drug Interaction Prediction',
    summary: 'AlphaFold 3 can now predict how drug molecules interact with protein targets, potentially cutting drug discovery timelines from years to months.',
    source: 'MIT Tech Review',
    category: 'ai',
    subtopic: 'Research',
    url: '#',
    publishedAt: hours(4),
    readTime: 6,
  },
  {
    id: 'ai-3',
    title: 'AI Code Editor Cursor Raises $400M at $9B Valuation',
    summary: 'The VS Code fork powered by AI pair programming has become one of the fastest-growing developer tools, now used by 3 million developers daily.',
    source: 'TechCrunch',
    category: 'ai',
    subtopic: 'Startups',
    url: '#',
    publishedAt: hours(5),
    readTime: 4,
  },
  {
    id: 'ai-4',
    title: 'Meta Releases Llama 4 Maverick Open-Source with MoE Architecture',
    summary: 'Llama 4 Maverick uses a mixture-of-experts design with 400B total parameters but only 17B active. Performance rivals GPT-4o at a fraction of the compute cost.',
    source: 'VentureBeat',
    category: 'ai',
    subtopic: 'Models',
    url: '#',
    publishedAt: hours(6),
    readTime: 5,
  },
  {
    id: 'ai-5',
    title: 'Microsoft Integrates AI Agents Into Every Office 365 App',
    summary: 'Copilot Agents can now autonomously draft reports, schedule meetings, and manage email across Word, Excel, Outlook, and Teams with minimal user input.',
    source: 'The Verge',
    category: 'ai',
    subtopic: 'Companies',
    url: '#',
    publishedAt: hours(7),
    readTime: 4,
  },

  // ── CRYPTO ──
  {
    id: 'cr-1',
    title: 'Ethereum Layer 2 TVL Surpasses $80B After Base and Arbitrum Surge',
    summary: 'Combined L2 TVL hit an all-time high as Base processed 15M daily transactions. Blob fees remain under $0.01, making DeFi accessible to retail users.',
    source: 'The Block',
    category: 'crypto',
    subtopic: 'L1/L2',
    url: '#',
    publishedAt: hours(2),
    readTime: 4,
  },
  {
    id: 'cr-2',
    title: 'Uniswap v4 Hooks Unlock Custom AMM Logic, TVL Jumps 40%',
    summary: 'The new hooks system lets developers create custom pool behaviors—dynamic fees, TWAP orders, and on-chain limit orders—driving a wave of DeFi innovation.',
    source: 'Decrypt',
    category: 'crypto',
    subtopic: 'DeFi',
    url: '#',
    publishedAt: hours(3),
    readTime: 4,
  },
  {
    id: 'cr-3',
    title: 'Polymarket Hits $500M Monthly Volume Ahead of Elections',
    summary: 'The prediction market platform sees record engagement as users bet on political, economic, and tech outcomes. Regulatory clarity in the US has boosted adoption.',
    source: 'CoinDesk',
    category: 'crypto',
    subtopic: 'Prediction Markets',
    url: '#',
    publishedAt: hours(4),
    readTime: 3,
  },
  {
    id: 'cr-4',
    title: 'Solana Memecoin Frenzy: New Token Hits $2B Market Cap in 48 Hours',
    summary: 'A community-driven memecoin on Solana captured viral attention, raising questions about speculation vs. genuine community building in crypto.',
    source: 'Decrypt',
    category: 'crypto',
    subtopic: 'Memecoins',
    url: '#',
    publishedAt: hours(5),
    readTime: 3,
  },
  {
    id: 'cr-5',
    title: 'BlackRock Tokenizes $2B Treasury Fund on Ethereum via Securitize',
    summary: 'The world\'s largest asset manager expands its BUIDL fund, signaling that real-world asset tokenization is moving from pilot to production scale.',
    source: 'Bloomberg',
    category: 'crypto',
    subtopic: 'RWA',
    url: '#',
    publishedAt: hours(5),
    readTime: 4,
  },
  {
    id: 'cr-6',
    title: 'Helium Network Crosses 2M Hotspots as DePIN Gains Traction',
    summary: 'Decentralized wireless infrastructure continues expanding, with Helium Mobile adding 500K subscribers. Revenue-generating DePIN protocols attract institutional interest.',
    source: 'The Block',
    category: 'crypto',
    subtopic: 'DePIN',
    url: '#',
    publishedAt: hours(6),
    readTime: 4,
  },
  {
    id: 'cr-7',
    title: 'Immutable zkEVM Sees 10x Growth in Gaming Transactions',
    summary: 'AAA game studios are deploying on Immutable\'s gaming-focused L2, with transaction volumes jumping from 2M to 20M monthly in Q1.',
    source: 'CoinDesk',
    category: 'crypto',
    subtopic: 'GameFi',
    url: '#',
    publishedAt: hours(7),
    readTime: 3,
  },
  {
    id: 'cr-8',
    title: 'Sui and Aptos Lead New Wave of Move-Based L1 Adoption',
    summary: 'Move-language blockchains see DeFi TVL double in 30 days as developers praise the safety guarantees and parallel execution model.',
    source: 'The Block',
    category: 'crypto',
    subtopic: 'Altcoins',
    url: '#',
    publishedAt: hours(8),
    readTime: 4,
  },

  // ── INVESTMENT ──
  {
    id: 'inv-1',
    title: 'Gold Hits All-Time High of $2,850/oz on Geopolitical Uncertainty',
    summary: 'Safe-haven demand drives gold to record levels as central banks continue accumulating reserves. Analysts project $3,000 by year-end.',
    source: 'Reuters',
    category: 'investment',
    subtopic: 'Gold',
    url: '#',
    publishedAt: hours(2),
    readTime: 3,
  },
  {
    id: 'inv-2',
    title: 'Silver Surges 8% as Industrial AI Demand Outpaces Mining Supply',
    summary: 'Silver\'s dual role as precious metal and industrial input (AI chip manufacturing, solar panels) creates a structural supply deficit for the first time in a decade.',
    source: 'Financial Times',
    category: 'investment',
    subtopic: 'Silver',
    url: '#',
    publishedAt: hours(3),
    readTime: 4,
  },
  {
    id: 'inv-3',
    title: 'Magnificent 7 Stocks Rally: Combined Market Cap Exceeds $18 Trillion',
    summary: 'Apple, Microsoft, NVIDIA, Amazon, Alphabet, Meta, and Tesla collectively gained $1.2T in Q1 as AI spending drove revenue beats across the board.',
    source: 'CNBC',
    category: 'investment',
    subtopic: 'Tech Stocks',
    url: '#',
    publishedAt: hours(4),
    readTime: 5,
  },
  {
    id: 'inv-4',
    title: 'US Inflation Drops to 2.4%, Lowest Since Early 2021',
    summary: 'CPI data shows continued disinflation driven by falling energy and used car prices. Core services inflation remains sticky at 3.8%, keeping the Fed cautious.',
    source: 'Bloomberg',
    category: 'investment',
    subtopic: 'Macro Economy',
    url: '#',
    publishedAt: hours(5),
    readTime: 4,
  },
  {
    id: 'inv-5',
    title: 'S&P 500 Closes Above 6,000 for First Time in History',
    summary: 'Broad market gains push the index past a psychological milestone. AI infrastructure spending and strong earnings drive optimism despite elevated valuations.',
    source: 'Reuters',
    category: 'investment',
    subtopic: 'Market Movements',
    url: '#',
    publishedAt: hours(3),
    readTime: 3,
  },
  {
    id: 'inv-6',
    title: 'China Stimulus Package Boosts Emerging Market Sentiment',
    summary: 'Beijing announces a $500B infrastructure and tech investment plan. Hang Seng rallies 4% as global funds rotate into undervalued Chinese equities.',
    source: 'Financial Times',
    category: 'investment',
    subtopic: 'Macro Economy',
    url: '#',
    publishedAt: hours(6),
    readTime: 4,
  },
];
